manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: iwk7273
      url-base: https://github.com/iwk7273
  projects:
    - name: zmk
      remote: iwk7273
      revision: ec0b331245f62c98e26b950e8d5ad46bc43cf91e
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: iwk7273
      revision: main
    - name: zmk-feature-meteorite-config
      remote: iwk7273
      revision: 22cfbc10de40258b9082a2e0e1e976497d20835a
  self:
    path: config
