manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: iwk7273
      url-base: https://github.com/iwk7273
  projects:
    - name: zmk
      remote: iwk7273
      revision: 08d8238f9098804e97aa5169f4cc6dcb8e36d7fd
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: iwk7273
      revision: main
    - name: zmk-feature-meteorite-config
      remote: iwk7273
      revision: 02e3cffc3f7785af3f699ed8e6171a9fb8ccd5a2
  self:
    path: config
